### PR TITLE
Install php7-exif extensions

### PR DESCRIPTION
**Pull request by iiska**
Enables exif metadata use with Piwigo and gets rid of related error notifications in the Admin UI.

### CODE REVIEW

**Comment by sparklyballs** [comment]
jenkins please test this

**Comment by sparklyballs** [comment]
jenkins test this please

**Comment by sparklyballs** [comment]
hi @iiska could you possibly add this line 

`+**20.04.17:** Add php7-exif package, thanks iiska`

above the line

`+ **23.02.17:** Rebase to alpine linux 3.5 and nginx.`

in the versions section of the README, thanks..

**Comment by iiska** [comment]
Hi, I added the changelog entry and rebased my changes to a single commit to avoid trashing your history with unnecessary extra commits.

**Comment by sparklyballs** [comment]
thanks for the changes and the squash

**Pull request merged**
