### PR TITLE
Increase upload_max_filesize in php.ini

### LINKED ISSUE #30: The upload_max_filesize is too low
The value of upload_max_filesize defined in the php.ini file is very low (2M). This causes the upload of big pictures from the android app to fail with the error message: "Failed to move uploaded file".

Please see: https://github.com/Piwigo/Piwigo-Android/issues/217

I suggest increasing it a bit. Currenly, as I workaround, I override the value by setting it in the php-local.ini file, which is persisted across restarts of the container

### PR DESCRIPTION
**Pull request by blastrock**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-piwigo/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
This PR increases the upload_max_filesize and max_post_size.

## Benefits of this PR and context:
The current maximum are 2M and 8M respectively, which are way too low. Most photos are bigger than that.

Closes #30 

## How Has This Been Tested?

I tested this only on x86_64.
I have built the image without cache and run it.
I managed to successfully upload big pictures both through the Web UI and through darktable (which was my initial use-case).

## Source / References:

- https://www.php.net/manual/en/ini.core.php#ini.upload-max-filesize
- https://www.php.net/manual/en/ini.core.php#ini.post-max-size

### CODE REVIEW

**Comment by aptalca** [comment]
Thanks for the PR, but it would be better to do the sed in the dockerfiles so it's taken care of build time and not runtime

**Comment by blastrock** [comment]
Done, but I can't test it though, the image seems broken now:

```
Step 7/12 : RUN  echo "**** install packages ****" &&  apk add --no-cache --upgrade     curl    exiftool        ffmpeg  imagemagick     libjpeg-turbo-utils     lynx    mediainfo       php7-apcu       php7-cgi        php7-ctype      php7-curl       php7-dom        php7-exif       php7-gd   php7-imagick     php7-ldap       php7-mysqli     php7-mysqlnd    php7-pear       php7-xmlrpc     php7-xsl        poppler-utils   re2c    unzip   wget &&  echo "**** download piwigo ****" &&  if [ -z ${PIWIGO_RELEASE+x} ]; then       PIWIGO_RELEASE=$(curl -sX GET "https://api.github.com/repos/Piwigo/Piwigo/releases/latest"         | awk '/tag_name/{print $4;exit}' FS='[""]');  fi &&  mkdir /piwigo &&  curl -o         /piwigo/piwigo.zip -L    "http://piwigo.org/download/dlcounter.php?code=${PIWIGO_RELEASE}"
 ---> Running in 1598416084dc
**** install packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  so:libMagickCore-7.Q16HDRI.so.7 (missing):
    required by: php7-pecl-imagick-3.4.4-r3[so:libMagickCore-7.Q16HDRI.so.7]
  so:libMagickWand-7.Q16HDRI.so.7 (missing):
    required by: php7-pecl-imagick-3.4.4-r3[so:libMagickWand-7.Q16HDRI.so.7]
```

**Comment by aptalca** [comment]
The build error was a temporary glitch with the alpine repo. It's building fine now.

Can you move the sed lines into the same RUN block as the package installs? That way it doesn't duplicate the files in separate layers.

Thanks

**Comment by blastrock** [comment]
Done. It builds now indeed, tested on x86 only.

**Review by aptalca — APPROVED** [review]

**Comment by aptalca** [comment]
Excellent, thanks

**Comment by blastrock** [comment]
Thank you for merging this! :)

**Pull request merged**
